---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: udalocation-app
  name: kafka-repcon
spec:
  replicas: 1
  selector:
    app: udalocation-app
  template:
    metadata:
      labels:
        app: udalocation-app
    spec:
      containers:
        -
          command:
            - zookeeper-server-start.sh
            - /config/zookeeper.properties
          image: "wurstmeister/kafka"
          name: udalocation-app
          ports:
            -
              containerPort: 2181
