apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka-service
  name: kafka
spec:
  ports:
  - name: kafka
    port: 9092
    protocol: TCP
    targetPort: 9092
    nodePort: 30005  
  selector:
    service: kafka-service
  type: NodePort