apiVersion: v1
kind: Service
metadata:
  labels:
    service: udalocation-api
  name: udalocation-api
spec:
  ports:
  - name: "5001"
    port: 5001
    targetPort: 5000
    nodePort: 30001
  selector:
    service: udalocation-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udalocation-api
  name: udalocation-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udalocation-api
  template:
    metadata:
      labels:
        service: udalocation-api
    spec:
      containers:
      - image: morderngeek/u_locate:latest
        name: udalocation-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
