apiVersion: v1
kind: Service
metadata:
  labels:
    service: udalocation-app
  name: udalocation-app
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3000
    nodePort: 30002
  - name: zookeeper
    port: 2181
    protocol: TCP
    targetPort: 2181
    nodePort: 30002  
  selector:
    service: udalocation-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udalocation-app
  name: udalocation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udalocation-app
  template:
    metadata:
      labels:
        service: udalocation-app
    spec:
      containers:
      - name:zoo
        image:bitnami/zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zoo
                  
      - image: morderngeek/u_locate:latest
        name: udaconnect-app
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "256m"
      restartPolicy: Always
