apiVersion: v1
kind: Service
metadata:
  labels:
    service: udapersons-api
  name: udapersons-api
spec:
  ports:
  - name: "5002"
    port: 5002
    targetPort: 5000
    nodePort: 30005
  selector:
    service: udapersons-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udapersons-api
  name: udapersons-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udapersons-api
  template:
    metadata:
      labels:
        service: udapersons-api
    spec:
      containers:
      - image: morderngeek/u_persons:latest
        name: udapersons-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
