apiVersion: v1
kind: Service
metadata:
  labels:
    service: udapersons-app
  name: udapersons-app
spec:
  ports:
  - name: "3002"
    port: 3002
    targetPort: 3000
    nodePort: 30004
  selector:
    service: udapersons-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udapersons-app
  name: udapersons-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udapersons-app
  template:
    metadata:
      labels:
        service: udapersons-app
    spec:
      containers:
      - image: morderngeek/u_persons:latest
        name: udaconnect-app
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "256m"
      restartPolicy: Always
